using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Z80Sharp.Enums
{
    public enum LogSeverity
    {
        /// <summary>
        /// Processor debug information.
        /// </summary>
        Debug,

        /// <summary>
        /// General information outputted by the processor.
        /// </summary>
        Info,

        /// <summary>
        /// Logs generated by memory accesses
        /// </summary>
        Memory,

        /// <summary>
        /// A warning generated by the processor.
        /// </summary>
        Warning,

        /// <summary>
        /// Unrecoverable events use this, such as an unknown opcode.
        /// </summary>
        Fatal
    }
}
